config/routes.rb
Rails.application.routes.draw do
  
  
    get 'admin' => 'admin#index'

    
  scope '(:locale)' do
    root 'store#index', :as => 'store'
    devise_for :users,
               :controllers => {:registrations => "my_devise/registrations"}
    resources :orders
    resources :line_items
    resources :carts
    resources :products do 
        get :who_bought, :on => :member
        collection do
          get :search
        end
    end
  end

  

end

app/models/product.rb
class Product < ActiveRecord::Base

	default_scope -> {order(:title)}
	belongs_to :user
	has_many :line_items
	has_many :orders, :through => :line_items
	before_destroy :ensure_not_referenced_by_any_line_item

	validates :title, :description, :image_url, :price, presence: true
	validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
	validates :title, uniqueness: true
	validates :image_url, :format => {:with => /(\.(gif|jpg|png)$)/i, :message => 'must be a URL for GIF, JPG or PNG image.'}

	def self.search(query)  
	    if query  
	      where('title LIKE ?', "%#{query}%")  
	    else  
	      where(nil) 
	    end  
  	end 

	private

	def ensure_not_referenced_by_any_line_item
		if line_items.empty?
			return true
		else
			errors.add(:base, 'Line Items present')
			return false
		end 
	end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
   helper_method :sort_column, :sort_direction
  before_action :authenticate_user!, except: :index
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @cart = current_cart
    
    @products =  Product.search(params[:search]).paginate(:per_page => 10, :page => params[:page])
    if @products.empty?
      @search_notice = "No Results found."
    else
      @search_notice = "Your Search yielded #{@products.count} results."
    end 

  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  def who_bought
    @product = Product.find(params[:id]) 
    respond_to do |format|
      format.atom
      format.xml { render :xml => @product }
    end 
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.build(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price)
    end


    def sort_column
     Product.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end
  
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, :rows => 6 %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<% if notice %>
	<p id="notice"><%= notice %></p> 
<% end %>
<div id= "search-result">
<div>
	<%= form_tag products_path, :method => 'get', :id => 'product_search' do %>  
	  <p>  
	    <%= text_field_tag :search, params[:search], :placeholder => "Search Product by Title" %>  
	    <%= submit_tag "Search", :name => nil %>  
	  </p>  
	<% end %> 
	<%= will_paginate %>
</div>


<h1>Your Pragmatic Catalog</h1>
<h4 style="color:red"> <%= @search_notice %></h4>
      
<% @products.each do |product| %>
	<div class="entry"><br />
		<%= image_tag(product.image_url) %> 
		<h3><%= product.title %></h3>
		<%= sanitize(product.description) %> 

		<div class="price_line">
			<span class="price"><%= number_to_currency(product.price) %></span> 
			<div id="add_to_cart"><%= button_to 'Add to Cart', line_items_path(:product_id => product)%>
		</div>
	</div> <br />
<% end %>
<%= will_paginate %>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<% if notice %>
	<p id="notice"><%= notice %></p> 
<% end %>

<div>
	<%= form_tag products_path, :method => 'get' do %>  
	  <p>  
	    <%= text_field_tag :search, params[:search], :placeholder => "Search Product by Title" %>  
	    <%= submit_tag "Search", :name => nil %>  
	  </p>  
	<% end %> 
	<%= will_paginate %>
</div>


<h1>Your Pragmatic Catalog</h1>
<h4 style="color:red"> <%= @search_notice %></h4>
      
<% @products.each do |product| %>
	<div class="entry"><br />
		<%= image_tag(product.image_url) %> 
		<h3><%= product.title %></h3>
		<%= sanitize(product.description) %> 
		
		<div class="price_line">
			<span class="price"><%= number_to_currency(product.price) %></span> 
			<%= button_to 'Add to Cart', line_items_path(:product_id => product), :remote => true %>
		</div>
	</div> <br />
<% end %>
<%= will_paginate %>

app/views/products/index.js.erb
$('#search-result').html("<%= escape_javascript(render 'products') %>") 

<!-- this file is not updated yet -->

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>